---
title: "Hydrophones"
format: html
editor: 
  markdown: 
    wrap: 72
---

Over the years, acousticians at NMFS have utilized three different
hydrophone makers: APC- this consisted of a piezo-electric cylinder that
was hand soldered to the wires to create a hydrophone. Sensistivity was
uncharacterized and subject to the solderer's capability. This is the
least desirable of the hydrophone types NMFS uses.

Reson- these hydrophones have the best response curve in terms of being
flat across a broad range of frequencies (X-xx) but they are less
sensitive relative to HTIs

**HTI**- this is the hydrophone type that is currently preferred by the
NMFS science centers. While it does not have a flat frequency response,
a few models have been measured by Jay Barlow such that the response
curve is known. The model types that are used are:

*want to put images of these hydrophones before each number so that one
knows what they look like*

1\. HTI-96-Min: these are used in real-time towed hydrophone arrays
(flexible tube). Peak sensitivity is at 96 kHz

2\. HTI-99-HF: these were used in drifting recorders but are starting to
be phased out. *what is the positive/negatives of using this hydrophone
type*

3\. HTI-92-WB: used in drifting recorders and can be used in the
SoundTrap towed array (just 1). These are the most sensitive HTI
hydrophones and also the most expensive, but give you the best detection
ranges
