---
title: "Pin Testing - Deck and Tow Cables"
format: html
---

Pin testing of deck and tow cables should be completed before every cruise or field season.
You will need a buddy and a pin testing kit, which includes: 

1. Alligator clips to wires, alligator to alligator, alligator to 9V battery adaptor
2. Pins to wires (male and female) 
3. Multimeter 
4. Pin diagram 
5. Notebook – later going into Pin Testing Spreadsheet
6. 9V battery (for hydrophone and depth gauge testing) 

## Tow Cable 
### Male and Female Connector 

- Turn on the Multimeter to the setting on the right ‘ohm’ Ω, which measures resistance. Make sure your black and red cables are attached on the bottom right

- Attach alligator clips to the end of the multimeter red and black prongs (use the groove at the end). On the other end of the alligator clips should be pin adaptors, one a male pin and the other a female pin hole. 

- *If the tow cable is on the winch*, spool out the connector on the winch to a comfortable position and make sure the connector attached to the winch (by the pin) is easily accessible (not upside down) 

- Use your pin diagram to locate pin 1 on both the male and female connectors – use the notches as guides 

- Place your female pin hole onto the male pin 1, then do the reverse for pin 1 on the female end of the connector 

- Record the average reading from the multimeter (may jump around a bit) 
*The number itself is a relative reading, what you are looking for is consistency across all pins with none significantly lower than the other. Additionally, you should compare year to year to look for gradual drops in readings*

- Once complete, all number recordings should be entered into the Cable Pin Testing Excel Sheet located in the Cruise Folder 

## Deck Cable 
### Male connector and Components End (¼ jacks / battery power) 

- Turn on the Multimeter to the setting on the right ‘ohm’ Ω, which measures resistance. Make sure your black and red cables are attached on the bottom right side as well 

- Attach alligator clip to ONE end of the multimeter prongs (does not matter red or black), and attach a female pin adaptor 

- Coil your deck cable so that both connector ends are easily accessible and close to each other, with all jacks and power wires free 

- Use the pin diagram to locate pin 1 on the male connector, and the corresponding component on the other end of the deck cable, likely the primary power supply (battery connector)
    - Use the multimeter prong on the female side of the battery connector and record number, then move onto pin 2 on the male connector and switch to the (male) section of the battery power connector \*double check this section, male may be first 
*If desired, skip to pins 23 and 24 to test secondary power too*

- Then move to pins 3 and 4 and locate the corresponding deck cable component, likely a jack for the inline or end array. *Each jack will have a 'ring' and a 'tip' component, corresponding to two pins, it is important to know how your deck cable is wired before proceeding*
    - Ex: SEFSC deck cable is wired to ‘ring’ first, then ‘tip’, therefore the ring (center) will be pin 3, and the tip will be pin 4 
    
- Move the female pin adaptor to the corresponding prong on the deck cable connector, touch the male multimeter prong to the correct pin/tip on the jack. Record the number     

- Continue with this process across all rings and tips until you get to the depth sensor – *Sometimes the depth sensor is wired different* confirm wiring and complete as described above  

- Once complete, record all numbers in the corresponding data sheet to track over time 


*I have instructions to test the hydrophones in the array and the array depth gauge (based on Jennifer's instructions), where does that make the most sense to live??*
