---
title: "Real-time_tracking"
format: html
---

### TRACKING PROCESS

1.  Tracking animals will be done primarily through the click detector. Once you see a click train (3-5 consecutive clicks along the same bearing), start a detection in the Detection tab. Hit F1 to enter the time & date. Hit F1 to enter the Lat/long. Enter the Acoustic ID \# along with at least the initial bearing angle. You can fill out the other fields as the event goes on. There are 3 Detection tabs so that you can track 3 things at once. You can also use the TD tab to localize whistles.

    1.  For encounters in which there are both bearings from the whistles and clicks, you can merge them into one event by going to the map, holding down CTRL + left click and select “Assign X bearings to UID#”. You should then see both the whistle and click bearings as the same color. You may need to repeat this step over the course of the encounter.

2.  A mark should be placed at the start position on the trackline of the initial bearing location- clicks don’t stay on the map for long, the markers will last longer. Double click the spot on the map to enter “start of A#- \[species\]”

3.  Measuring the perpendicular distance from the ship’s track to the marked location can be done in the Map tab, by double-clicking next to the map comment and click + hold to the convergences (note: if you happen to select the pixel the map comment is on Pamguard won’t draw the measuring line). If you have R and L locations, measure on both sides of the ship’s track and take the average distance (this will be the beam distance). If you only have one location, take all measurements from the trackline to that location. Also measure the distance from the ship’s track along the first angle plotted that converged at the location (the first detection distance).

4.  Can you tie this detection to a visual sighting?? If so, be sure to record the visual ID, and any other info from the visual team in the comments field (time, bearing, distance, species ID, etc.).

    1.  Use the Visual to Array Angle module and the incoming information from the flying bridge to do so

5.  For marking the end of a detection, follow these general guidelines

    1.  Sperm whales: until 5 min have passed where no clicks are detected (can feel free to press F1 prior to this but keep the detection tab open for another 5 min)

    2.  Beaked whales: get an end time when 1 minute has passed without clicks. You will probably need to press F1 a few times as the clicks come back (thus constantly updating the end time)

    3.  Dolphins: if it’s just clicks, the end time is within 30s of the last click train. If it’s whistles and clicks, keep the detection open for up to 2 min after the last whistle. It’s common for whistle presence to come in and out

6.  Click “Save” to save this detection to the database.

    1.  If you end the encounter prematurely, you can double click on the row below the form to make any changes. Note that the F1 features do not work in this view. If the encounter’s row is not visible, you can make a comment using an asterisk (\*) in the User Input for later modification during the QAQC process.

7.  Look/listen for new groups. Continue to check bearings to sounds. Sometimes you will pick up a new group ahead of the ship while you are still hearing a group behind the ship.  Start a new Acoustic ID when another group is detected.  If a second group is detected before you have stored the info about the first group, you can save the first group and start a new group, then go back and edit the info for the 1st group when time allows.  Make note if long periods occur with no acoustic activity (i.e. “AQ”).
